# Generated by Django 2.2.28 on 2022-11-28 11:28

import apps.utils.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='公告的标题')),
                ('content', apps.utils.models.RichTextField(help_text='公告的具体内容')),
                ('visible', models.BooleanField(default=True, help_text='是否公开可见')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='公告创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, help_text='公告最近修改时间')),
                ('submitter', models.ForeignKey(help_text='创建人', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'engcase_announcement',
                'ordering': ('-last_update_time',),
            },
        ),
    ]
