# Generated by Django 2.2.28 on 2022-12-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.TextField(default='system_announcement', help_text='公告的类别'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='read_count',
            field=models.IntegerField(default=0, help_text='公告的浏览次数'),
        ),
    ]
