# Generated by Django 2.2.28 on 2022-12-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20221228_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.TextField(default='系统公告', help_text='公告的类别'),
        ),
    ]
