# Generated by Django 2.2.28 on 2024-03-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20221228_1011'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='announcement',
            table='announcement',
        ),
    ]
