# Generated by Django 2.2.28 on 2022-11-28 11:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(db_index=True, unique=True)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': '系统选项',
                'verbose_name_plural': '系统选项',
                'db_table': 'engcase_sysoptions',
                'ordering': ['id'],
            },
        ),
    ]
