# Generated by Django 2.2.28 on 2023-04-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APPInstallConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_path', models.CharField(help_text='App安装路径', max_length=1024)),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'App',
                'db_table': 'App_install_path',
                'ordering': ['id'],
            },
        ),
    ]
