# Generated by Django 2.2.28 on 2023-04-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_appinstallconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstallconfig',
            name='vncserver_path',
            field=models.CharField(default='', help_text='VNCserver路径', max_length=1024),
        ),
        migrations.AddField(
            model_name='appinstallconfig',
            name='vncserver_script_path',
            field=models.CharField(default='', help_text='VNCserver脚本路径', max_length=1024),
        ),
    ]
