# Generated by Django 2.2.28 on 2023-04-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_auto_20230404_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstallconfig',
            name='server_ip',
            field=models.CharField(default='', help_text='服务IP', max_length=1024),
        ),
    ]
