# Generated by Django 2.2.28 on 2023-04-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0004_appinstallconfig_server_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstallconfig',
            name='filebrowser_root',
            field=models.CharField(default='', help_text='filebrowser文件目录', max_length=1024),
        ),
    ]
