# Generated by Django 2.2.28 on 2023-04-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0005_appinstallconfig_filebrowser_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinstallconfig',
            name='filebrowser_root',
        ),
    ]
