# Generated by Django 2.2.28 on 2023-05-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0006_remove_appinstallconfig_filebrowser_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinstallconfig',
            name='vncserver_script_path',
            field=models.CharField(default='/opt/TurboVNC/scripts', help_text='VNCserver脚本路径', max_length=1024),
        ),
    ]
