# Generated by Django 2.2.28 on 2023-05-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0007_auto_20230506_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinstallconfig',
            name='vncserver_script_path',
            field=models.CharField(help_text='VNCserver脚本路径', max_length=1024),
        ),
    ]
