# Generated by Django 2.2.28 on 2023-06-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0008_auto_20230508_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinstallconfig',
            name='vncserver_path',
        ),
        migrations.RemoveField(
            model_name='appinstallconfig',
            name='vncserver_script_path',
        ),
    ]
