# Generated by Django 2.2.28 on 2023-08-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0009_auto_20230616_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstallconfig',
            name='vpn_config_file_path',
            field=models.CharField(default='', help_text='VPN配置文件路径', max_length=1024),
        ),
    ]
