# Generated by Django 2.2.28 on 2023-11-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0010_appinstallconfig_vpn_config_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinstallconfig',
            name='vpn_config_file_path',
        ),
    ]
