# Generated by Django 2.2.28 on 2023-11-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0011_remove_appinstallconfig_vpn_config_file_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APPInstallConfig',
        ),
    ]
