# Generated by Django 2.2.28 on 2024-03-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0012_delete_appinstallconfig'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sysoptions',
            table='sysoptions',
        ),
    ]
