# Generated by Django 2.2.28 on 2022-11-28 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoVNC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_number', models.IntegerField(help_text='display的序号', unique=True)),
                ('webserver_pid', models.IntegerField(help_text='webserver的进程号', unique=True)),
                ('run_software', models.CharField(help_text='桌面中启动的软件', max_length=1024)),
                ('novnc_url', models.URLField(help_text='novnc访问url', max_length=1024)),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='桌面启动时间')),
                ('server_starter', models.ForeignKey(help_text='桌面的启动人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vncserver_starter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '远程桌面',
                'verbose_name_plural': '远程桌面',
                'db_table': 'novnc_info',
                'ordering': ['display_number'],
            },
        ),
    ]
