# Generated by Django 2.2.28 on 2023-03-10 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vncserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='App名称', max_length=1024)),
                ('version', models.CharField(help_text='App版本', max_length=1024)),
                ('install_path', models.CharField(help_text='App安装路径', max_length=1024)),
                ('run_bash_path', models.CharField(help_text='App启动脚本路径', max_length=1024)),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='App被添加的时间')),
                ('visible', models.BooleanField(default=True, help_text='是否可见')),
                ('change_time', models.DateTimeField(auto_now=True, help_text='App被更改的时间')),
                ('App_creator', models.ForeignKey(help_text='App的创建人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='App_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'App',
                'db_table': 'App_manager',
                'ordering': ['id'],
            },
        ),
    ]
