# Generated by Django 2.2.28 on 2023-03-13 13:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vncserver', '0002_appmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmanager',
            name='user_manual',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_index=True, default=dict, null=True),
        ),
    ]
