# Generated by Django 2.2.28 on 2023-03-28 16:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vncserver', '0003_appmanager_user_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmanager',
            name='app_package',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_index=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='appmanager',
            name='auth_code',
            field=models.CharField(default='', help_text='安装包授权码', max_length=1024),
        ),
        migrations.AddField(
            model_name='appmanager',
            name='bin_path',
            field=models.CharField(default='', help_text='可执行文件路径', max_length=1024),
        ),
        migrations.AlterField(
            model_name='appmanager',
            name='run_bash_path',
            field=models.CharField(default='', help_text='App启动脚本路径', max_length=1024),
        ),
    ]
