# Generated by Django 2.2.28 on 2023-03-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vncserver', '0004_auto_20230328_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmanager',
            name='install_status',
            field=models.CharField(default='未安装', help_text='安装状态', max_length=1024),
        ),
    ]
