# Generated by Django 2.2.28 on 2023-03-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vncserver', '0005_appmanager_install_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmanager',
            name='install_log',
            field=models.CharField(default='未安装', help_text='安装日志', max_length=1024),
        ),
    ]
