# Generated by Django 2.2.28 on 2023-03-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vncserver', '0006_appmanager_install_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmanager',
            name='auth_code',
            field=models.CharField(help_text='安装包授权码', max_length=1024),
        ),
        migrations.AlterField(
            model_name='appmanager',
            name='bin_path',
            field=models.CharField(help_text='可执行文件路径', max_length=1024),
        ),
        migrations.AlterField(
            model_name='appmanager',
            name='install_log',
            field=models.CharField(help_text='安装日志', max_length=1024),
        ),
        migrations.AlterField(
            model_name='appmanager',
            name='install_status',
            field=models.CharField(help_text='安装状态', max_length=1024),
        ),
        migrations.AlterField(
            model_name='appmanager',
            name='run_bash_path',
            field=models.CharField(help_text='App启动脚本路径', max_length=1024),
        ),
    ]
