# Generated by Django 2.2.28 on 2023-04-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vncserver', '0007_auto_20230330_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmanager',
            name='complete_path',
            field=models.CharField(default='', help_text='APP的完整路径', max_length=1024),
        ),
    ]
