# Generated by Django 2.2.28 on 2023-05-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vncserver', '0008_appmanager_complete_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appmanager',
            name='run_bash_path',
        ),
    ]
