# Generated by Django 2.2.28 on 2024-02-29 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vncserver', '0009_remove_appmanager_run_bash_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='VNCSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='vnc session ID', max_length=1024)),
                ('display_number', models.IntegerField(help_text='display的序号', unique=True)),
                ('run_software', models.CharField(help_text='桌面中启动的软件', max_length=1024)),
                ('novnc_url', models.URLField(help_text='novnc访问url', max_length=1024)),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='桌面启动时间')),
                ('server_starter', models.ForeignKey(help_text='桌面的启动人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vncserver_starter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '远程桌面',
                'verbose_name_plural': '远程桌面',
                'db_table': 'vnc_session_info',
                'ordering': ['display_number'],
            },
        ),
        migrations.DeleteModel(
            name='NoVNC',
        ),
    ]
