# Generated by Django 2.2.28 on 2024-06-06 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vncserver', '0010_auto_20240229_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmanager',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='App名称版本', max_length=1024),
            preserve_default=False,
        ),
    ]
