# Generated by Django 2.2.28 on 2022-11-30 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='testcase_submission_number',
            new_name='started_display_count',
        ),
    ]
