# Generated by Django 2.2.28 on 2023-08-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20221130_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sym_talk_user_id',
            field=models.TextField(null=True),
        ),
    ]
