# Generated by Django 2.2.28 on 2023-09-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_sym_talk_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_passwd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='old_passwd',
            field=models.TextField(null=True),
        ),
    ]
