# Generated by Django 2.2.28 on 2023-09-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230901_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='new_passwd',
        ),
        migrations.RemoveField(
            model_name='user',
            name='old_passwd',
        ),
        migrations.AddField(
            model_name='user',
            name='encrypt_passwd',
            field=models.TextField(null=True),
        ),
    ]
