# Generated by Django 2.2.28 on 2023-11-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20230901_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sym_talk_user_id',
        ),
    ]
