# Generated by Django 2.2.28 on 2023-12-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_user_sym_talk_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='open_api',
        ),
        migrations.RemoveField(
            model_name='user',
            name='open_api_appkey',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_password_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_password_token_expire_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tfa_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_auth',
        ),
    ]
