"""
Django settings for VNC project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
import os

import raven
from celery.schedules import crontab

from apps.utils.shortcuts import get_env

production_env = get_env("VNC_ENV", "dev") == "production"
if production_env:
    from .production_settings import *  # noqa
else:
    from .develop_settings import *  # noqa

# # SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "007pxm%d0@sgaq9claz14szpe0eof3+++ob+g*#42m3=eu*z8o"

# with open(os.path.join(DATA_DIR, "config", "secret.key"), "r") as f:  # noqa
#     SECRET_KEY = f.read()

# Application definition

VENDOR_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "treebeard",  # 处理层级关系
    "rest_framework",
    "django_dramatiq",
    "django_dbconn_retry",  # 数据库重连
]

if production_env:
    VENDOR_APPS.append("raven.contrib.django.raven_compat")
    # 日志收集的功能(sentry),先在暂时未具体实现（离线环境需要自己搭建）


LOCAL_APPS = [
    "apps.account",
    "apps.announcement",
    "apps.conf",
    "apps.vncserver",
    "apps.utils"
]

INSTALLED_APPS = VENDOR_APPS + LOCAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # compress, ref: https://openfolder.sh/django-faster-speed-tutorial
    "compression_middleware.middleware.CompressionMiddleware",  # 对传输数据做压缩，减小通讯量
    # local middleware
    "apps.account.middleware.AdminRoleRequiredMiddleware",
    "apps.account.middleware.SessionRecordMiddleware",
    # 开启对 sql 查询语句的输出
    # 'apps.account.middleware.LogSqlMiddleware',
]

ROOT_URLCONF = "apps.novncdb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "apps.novncdb.wsgi.application"

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "en-us"

# TIME_ZONE = 'UTC'
TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_L10N = True

USE_TZ = False

AUTH_USER_MODEL = "account.User"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# 管理配置
VNCSERVER_SCRIPT_PATH = os.environ.get("START_APP_SCRIPTS_DIR", "/opt/scns_apps_platform/thirdparty/app_start_scripts")
OPENBOX_DIR = os.environ.get("OPENBOX_DIR", "/opt/scns_apps_platform/thirdparty/OpenBox")
VIRTUALGL_DIR = os.environ.get("VIRTUALGL_DIR", "/opt/scns_apps_platform/thirdparty/VirtualGL")
VNC_SESSION_MANAGER_URL = os.environ.get("VNC_SESSION_MANAGER_URL", "http://0.0.0.0:8000")
VNC_SESSION_MANAGER_URLS = os.environ.get("VNC_SESSION_MANAGER_URLS", "http://node1:8000,http://node2:8000,http://node3:8000").split(",")
USER_MANAGEMENT_HOST = os.environ.get("USER_MANAGEMENT_HOST", "http://0.0.0.0:9000")
NOVNC_TARGET_PATH = os.environ.get("NOVNC_TARGET_PATH", "/opt/scns_apps_platform/thirdparty/noVNC") 


# 存放公共的文件
STATIC_URL = "/public/"

# 存放头像图片等
AVATAR_URI_PREFIX = "/public/avatar"
AVATAR_UPLOAD_DIR = "{}{}".format(DATA_DIR, AVATAR_URI_PREFIX)  # noqa

# 存放Logo图片
LOGO_URI_PREFIX = "/public/logo"
LOGO_UPLOAD_DIR = "{}{}".format(DATA_DIR, LOGO_URI_PREFIX)  # noqa

# 存放 文本编辑器 上传的图片、文件等
UPLOAD_PREFIX = "/public/upload"
UPLOAD_DIR = "{}{}".format(DATA_DIR, UPLOAD_PREFIX)  # noqa

# 存放与vnc服务相关的所有文件
PUBLIC_DIR = os.path.join(DATA_DIR, "public")
NOVNC_DIR = os.path.join(PUBLIC_DIR, "novncfiles")  # noqa

# 存放用户手册文件
MANUAL_DIR = os.path.join(NOVNC_DIR, "manualfiles")  # noqa

# store register excel file
REGISTER_DIR = os.path.join(PUBLIC_DIR, "register")

# 存放App安装包文件
PKG_DIR = os.path.join(NOVNC_DIR, "pkgfiles")  # noqa

# 存放安装日志
INSTALL_LOG_DIR = os.path.join(NOVNC_DIR, "installlogs")  # noqa

# 临时文件路径
TMP_DIR = os.path.join(NOVNC_DIR, "tmp")

# 存放APP启动脚本文件
APP_STARTUP_SCRIPTS = os.path.join(os.path.abspath(os.path.dirname(DATA_DIR)), "app_startup_scripts")

STATICFILES_DIRS = [os.path.join(DATA_DIR, "public"), NOVNC_DIR]  # noqa

# logging
LOGGING_HANDLERS = ["console", "sentry"] if production_env else ["console"]
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "[%(asctime)s] - [%(levelname)s] - [%(name)s:%(lineno)d]  - %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        }
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        "sentry": {
            "level": "ERROR",
            "class": "raven.contrib.django.raven_compat.handlers.SentryHandler",
            "formatter": "standard",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": LOGGING_HANDLERS,
            "level": "ERROR",
            "propagate": True,
        },
        "django.db.backends": {
            "handlers": LOGGING_HANDLERS,
            "level": "ERROR",
            "propagate": True,
        },
        "dramatiq": {
            "handlers": LOGGING_HANDLERS,
            "level": "DEBUG",
            "propagate": False,
        },
        "": {
            "handlers": LOGGING_HANDLERS,
            "level": "WARNING",
            "propagate": True,
        },
    },
}

# REST_FRAMEWORK 相关设定 具体查看DRF官方文档
REST_FRAMEWORK = {
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
    )
}

# redis url 配置
REDIS_URL = "redis://{}:{}".format(REDIS_CONF["host"], REDIS_CONF["port"])  # noqa


def redis_config(db):
    # 配置缓存所用的 redis 数据库
    def make_key(key, key_prefix, version):
        return key

    return {
        "BACKEND": "apps.utils.cache.MyRedisCache",
        "LOCATION": os.path.join(REDIS_URL, str(db)),
        "TIMEOUT": None,
        "KEY_PREFIX": "",
        "KEY_FUNCTION": make_key,
    }


CACHES = {"default": redis_config(db=1)}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# 设置 dramatiq
DRAMATIQ_BROKER = {
    "BROKER": "dramatiq.brokers.redis.RedisBroker",
    "OPTIONS": {"url": os.path.join(REDIS_URL, "4")},
    "MIDDLEWARE": [
        "dramatiq.middleware.Prometheus",
        "dramatiq.middleware.AgeLimit",
        "dramatiq.middleware.TimeLimit",
        "dramatiq.middleware.Callbacks",
        "dramatiq.middleware.Retries",
        "django_dramatiq.middleware.AdminMiddleware",
        "django_dramatiq.middleware.DbConnectionsMiddleware",
    ],
}

DRAMATIQ_RESULT_BACKEND = {
    "BACKEND": "dramatiq.results.backends.redis.RedisBackend",
    "BACKEND_OPTIONS": {"url": os.path.join(REDIS_URL, "4")},
    "MIDDLEWARE_OPTIONS": {"result_ttl": None},
}

IP_HEADER = "HTTP_X_REAL_IP"

# settings.py
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'

# 重要：允许长时间任务
CELERY_TASK_TIME_LIMIT = 120
CELERY_TASK_SOFT_TIME_LIMIT = 100

# Celery Beat 定时任务配置
CELERY_BEAT_SCHEDULE = {
    'cleanup-expired-sessions-weekly': {
        'task': 'vnc.cleanup_expired_sessions',
        # 每周一凌晨 2 点执行
        'schedule': crontab(hour=2, minute=0, day_of_week=1),
    },
}